config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :professors do
    resources :reviews
  end

  resources :my_classes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_class.rb
class MyClass < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_and_belongs_to_many :professors
  has_many :reviews, dependent: :destroy
end

app/models/professor.rb
class Professor < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_and_belongs_to_many :my_classes
  has_many :reviews, dependent: :destroy

  def full_name
    "#{last_name}, #{first_name}"
  end

  def average_rating_for(my_class)
    reviews.where({my_class_id: my_class.id}).average(:rating).try(:truncate, 2)
  end

  def average_rating
    reviews.average(:rating).try(:truncate, 2)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  RATING_SCALE = 1..5

  validates :rating, presence: true

  belongs_to :professor
  belongs_to :my_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/my_classes_controller.rb
class MyClassesController < ApplicationController
  before_action :set_my_class, only: [:show, :edit, :update, :destroy]
  before_action :set_professors, only: [:new, :create, :edit, :update]

  # GET /my_classes
  def index
    @my_classes = MyClass.all
  end

  # GET /my_classes/1
  def show
  end

  # GET /my_classes/new
  def new
    @my_class = MyClass.new
  end

  # GET /my_classes/1/edit
  def edit
  end

  # POST /my_classes
  def create
    @my_class = MyClass.new(my_class_params)

    if @my_class.save
      @my_class.professor_ids = professor_ids
      redirect_to @my_class, notice: 'Class was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /my_classes/1
  def update
    if @my_class.update(my_class_params)
      @my_class.professor_ids = professor_ids
      redirect_to @my_class, notice: 'Class was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /my_classes/1
  def destroy
    @my_class.destroy
    redirect_to my_classes_url, notice: 'Class was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_class
      @my_class = MyClass.find(params[:id])
    end

    def set_professors
      @professors = Professor.all
    end

    # Only allow a trusted parameter "white list" through.
    def my_class_params
      params.require(:my_class).permit(:name)
    end

    def professor_ids
      params[:my_class][:professor_ids].reject { |id| id.blank? }
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :set_classes, only: [:new, :create, :edit, :update]

  # GET /professors
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      @professor.my_class_ids = class_ids
      redirect_to @professor, notice: 'Professor was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /professors/1
  def update
    if @professor.update(professor_params)
      @professor.my_class_ids = class_ids
      redirect_to @professor, notice: 'Professor was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /professors/1
  def destroy
    @professor.destroy
    redirect_to professors_url, notice: 'Professor was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    def set_classes
      @my_classes = MyClass.all
    end

    # Only allow a trusted parameter "white list" through.
    def professor_params
      params.require(:professor).permit(:first_name, :last_name)
    end

    def class_ids
      params[:professor][:my_class_ids].reject { |id| id.blank? }
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_professor

  # GET /reviews
  def index
    @reviews = @professor.reviews
  end

  # GET /reviews/1
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to professor_path(@review.professor.id), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy
    redirect_to professor_reviews_url(@professor), notice: 'Review was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_professor
      @professor = Professor.find(params[:professor_id])
    end

    # Only allow a trusted parameter "white list" through.
    def review_params
      params.require(:review).permit(:rating, :description, :professor_id, :my_class_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title RateMyProf
    = csrf_meta_tags
    = csp_meta_tag
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-md.navbar-light.bg-light.fixed-top
      %a.navbar-brand{href: '#'} RateMyProf
      %button.navbar-toggler{type: 'button', data: {toggle: 'collapse', target: '#navbarMenu'}, aria: {controls: 'navbarMenu', expanded: 'false', label: 'Toggle navigation'}}
        %span.navbar-toggler-icon
      #navbarMenu.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.dropdown
            %a#myclass-dropdown.nav-link.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'}} Classes
            .dropdown-menu{aria: {labelledby: 'myclass-dropdown'}}
              = link_to 'Class List', my_classes_path, {class: 'dropdown-item'}
              = link_to 'New Class', new_my_class_path, {class: 'dropdown-item'}
          %li.nav-item.dropdown
            %a#prof-dropdown.nav-link.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'}} Professors
            .dropdown-menu{aria: {labelledby: 'prof-dropdown'}}
              = link_to 'Professor List', professors_path, {class: 'dropdown-item'}
              = link_to 'New Professor', new_professor_path, {class: 'dropdown-item'}

    %main.container{role: 'main'}
      - if notice
        #notice.alert.alert-info{role: 'alert'}= notice
      = yield

app/views/my_classes/_form.html.haml
= form_with(model: my_class, local: true) do |form|
  - if my_class.errors.any?
    #error_explanation.alert.alert-danger
      %b
        = pluralize(my_class.errors.count, "error")
        prohibited this class from being saved:

      %ul
      - my_class.errors.full_messages.each do |message|
        %li= message

  .form-group
    = form.label :name
    = form.text_field :name, {class: 'form-control'}

  .form-group.form-check
    = form.collection_check_boxes(:professor_ids, @professors, :id, :full_name) do |b|
      = b.check_box(class: 'form-check-input')
      = b.label(class: 'form-check-label')
      %br/

  = submit_tag 'Submit', class: 'btn btn-primary'

app/views/my_classes/edit.html.haml
= render 'form', my_class: @my_class

app/views/my_classes/index.html.haml
%h3 Classes

%table.table
  %thead
    %tr
      %th Name
      %th{:colspan => "2"}

  %tbody
    - @my_classes.each do |my_class|
      %tr
        %td= link_to my_class.name, my_class
        %td= link_to 'Edit', edit_my_class_path(my_class), {class: 'btn btn-secondary btn-sm', role: 'button'}
        %td= link_to 'Delete', my_class, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', role: 'button'

app/views/my_classes/new.html.haml
= render 'form', my_class: @my_class

app/views/my_classes/show.html.haml
%h3= @my_class.name

= link_to 'Edit', edit_my_class_path(@my_class), {class: 'btn btn-secondary btn-sm', role: 'button'}
= link_to 'Delete', @my_class, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', role: 'button'

%br/
%br/

%table.table
  %thead
    %tr
      %th Professor
      %th Average Rating
      %th
  %tbody
    - @my_class.professors.each do |p|
      %tr
        %td= link_to p.full_name, professor_path(p)
        %td= p.average_rating_for(@my_class)
        %td= link_to 'Review This Professor', new_professor_review_path(p.id), {class: 'btn btn-primary btn-sm', role: 'button'}

app/views/professors/_form.html.haml
= form_with(model: professor, local: true) do |form|
  - if professor.errors.any?
    #error_explanation.alert.alert-danger
      %b
        = pluralize(professor.errors.count, "error")
        prohibited this professor from being saved:
      %ul
        - professor.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :first_name
    = form.text_field :first_name, {class: 'form-control'}
  .form-group
    = form.label :last_name
    = form.text_field :last_name, {class: 'form-control'}

  .form-group.form-check
    = form.collection_check_boxes(:my_class_ids, @my_classes, :id, :name) do |b|
      = b.check_box(class: 'form-check-input')
      = b.label(class: 'form-check-label')
      %br/

  = submit_tag 'Submit', class: 'btn btn-primary'

app/views/professors/edit.html.haml
= render 'form', professor: @professor

app/views/professors/index.html.haml
%h3 Professors
%table.table
  %thead
    %tr
      %th Name
      %th{:colspan => "2"}
  %tbody
    - @professors.each do |professor|
      %tr
        %td= link_to professor.full_name, professor
        %td= link_to 'Edit', edit_professor_path(professor), {class: 'btn btn-secondary btn-sm', role: 'button'}
        %td= link_to 'Delete', professor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', role: 'button'

app/views/professors/new.html.haml
= render 'form', professor: @professor

app/views/professors/show.html.haml
%h3= @professor.full_name

%p
  %b Average Overall Rating: #{@professor.average_rating} (#{@professor.reviews.count} Reviews)

= link_to 'View All Reviews', professor_reviews_path(@professor), {class: 'btn btn-primary btn-sm', role: 'button'}
= link_to 'Edit', edit_professor_path(@professor), {class: 'btn btn-secondary btn-sm', role: 'button'}
= link_to 'Delete', @professor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', role: 'button'

%br/
%br/

%table.table
  %thead
    %tr
      %th Class
      %th Average Rating
  %tbody
    - @professor.my_classes.each do |c|
      %tr
        %td= link_to c.name, my_class_path(c)
        %td= @professor.average_rating_for(c)

app/views/reviews/_form.html.haml
= form_with(model: review, url: professor_reviews_path, local: true) do |form|
  - if review.errors.any?
    #error_explanation.alert.alert-danger
      %b
        = pluralize(review.errors.count, "error")
        prohibited this review from being saved:
      %ul
        - review.errors.full_messages.each do |message|
          %li= message

  %h3 Professor: #{@professor.full_name}
  = hidden_field_tag 'review[professor_id]', @professor.id

  .form-group
    = form.label 'Class'
    = form.collection_select :my_class_id, @professor.my_classes, :id, :name, {}, {class: 'form-control'}
  .form-group
    %p Rating (5 - excellent, 1 - worst)
    - Review::RATING_SCALE.each do |r|
      = form.label r
      = form.radio_button :rating, r
  .form-group
    = form.label :description
    = form.text_area :description, {class: 'form-control'}

  = submit_tag 'Submit', class: 'btn btn-primary'

app/views/reviews/edit.html.haml
%h1 Editing Review
= render 'form', review: @review
= link_to 'Show', @review
|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h3 Professor: #{@professor.full_name}
%table.table
  %thead
    %tr
      %th Class
      %th Rating
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.my_class.name
        %td= review.rating
        %td= review.description
        %td= link_to 'Delete', professor_review_path(@professor, review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm', role: 'button'

app/views/reviews/new.html.haml
= render 'form', review: @review, professor: @professor

app/views/reviews/show.html.haml
%p
  %strong Rating:
  = @review.rating
%p
  %strong Description:
  = @review.description
= link_to 'Edit', edit_review_path(@review)
|
= link_to 'Back', reviews_path